services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: predictick_postgres_dev
    restart: always
    environment:
      POSTGRES_DB: predictick_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: predictick_redis_dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata_dev:
    driver: local
  redisdata:
    driver: local