name: Backend CI/CD PipeLine

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-*.yml'

defaults:
  run:
    shell: bash
    working-directory: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U $${POSTGRES_USER}"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Restore application.yml from secret
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          touch ./application-dev.yml
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml
          echo "${{ secrets.DEV }}" > ./application-dev.yml
          echo "${{ secrets.PROD }}" > ./application-prod.yml

      - name: Make Docker Env
        run: |
          touch ./.env
          echo "${{ secrets.DOCKER_ENV }}" > ./.env

      - name: Verify resources layout & .env presence
        run: |
          set -euo pipefail
          echo "PWD: $(pwd)"
          echo "=== List src/main/resources ==="
          ls -la ./src/main/resources || true
          echo

          missing=0

          echo "=== Check required resource files ==="
          for f in application.yml application-dev.yml application-prod.yml; do
            if [ -f "./src/main/resources/$f" ]; then
              bytes=$(wc -c < "./src/main/resources/$f" | tr -d ' ')
              echo "✓ Found $f (${bytes} bytes)"
            else
              echo "✗ Missing $f"
              missing=1
            fi
          done
          echo

          echo "=== Check .env file existence ==="
          if [ -f ./.env ]; then
            bytes=$(wc -c < ./.env | tr -d ' ')
            echo "✓ Found .env (${bytes} bytes)"
            echo "→ Verifying required keys (length only, no values printed)"
            for key in JWT_SECRET ACCESS_TOKEN_EXPR REFRESH_TOKEN_EXPR; do
              if grep -E '^[[:space:]]*'"${key}"'[[:space:]]*=' ./.env >/dev/null; then
                val_len=$(grep -E '^[[:space:]]*'"${key}"'[[:space:]]*=' ./.env | head -n1 | sed -E 's/^[^=]+=//' | tr -d '\r\n' | wc -c | tr -d ' ')
                echo "  - ${key}: present (length ${val_len})"
              else
                echo "  - ${key}: MISSING"
                missing=1
              fi
            done
          else
            echo "✗ Missing .env"
            missing=1
          fi
          echo

          echo "=== Fail if anything missing ==="
          if [ "$missing" -ne 0 ]; then
            echo "Required files/keys are missing. Failing the job."
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          SPRING_PROFILES_ACTIVE: dev
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: ./gradlew build

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: backend/Dockerfile
          push: true
          tags: |
            jimineutron/notification_tick-backend:latest
            jimineutron/notification_tick-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    # 백엔드 코드 AWS EC2에 배포하는 로직 추가 예정!
    steps:
      - name: Notify Slack
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: '#00FF00'
          SLACK_TITLE: 'Build and Deploy'
          SLACK_TEXT: |
            ✅ 백엔드 이미지 푸시 성공
            - jimineutron/notification_tick-backend:${{ github.sha }}